#ifndef __485_ADDRESS__h
#define __485_ADDRESS__h
#include <stdint.h>

enum address_485_SCARA {

	/************************************************************************RO************************************************************************/
	SOFTWARE_VERSION = 0,
	MOTOR_TEMPERATURE,
	VBUS,
	POS_ESTIMATE_16HIGHER,
	POS_ESTIMATE_16LOWER,
	VEL_ESTIMATE_16HIGHER,
	VEL_ESTIMATE_16LOWER,
	RPM_ESTIMATE_16HIGHER,
	RPM_ESTIMATE_16LOWER,
	TORQUE_ESTIMATE_16HIGHER,
	TORQUE_ESTIMATE_16LOWER,
	RUNNING_MODE,
	// 轴只读参数
	CURRENT_REQUESTED_STATE = 12,
	LOCKIN_STATE,
	IS_HOMED,
	WATCHDOG_CURRENT_VALUE,
	AXIS_ERROR,
	// 编码器只读参数
	INDEX_FOUND = 17,
	ENCODER_IS_READY,
	SHADOW_COUNT_16HIGHER,
	SHADOW_COUNT_16LOWER,
	COUNT_IN_CPR_16HIGHER,
	COUNT_IN_CPR_16LOWER,
	ELECTRICAL_PHASE_16HIGHER,
	ELECTRICAL_PHASE_16LOWER,
	ENCODER_PLL_P_GAIN,
	ENCODER_PLL_I_GAIN,
	ENCODER_CURRENT_MODE,
	ENCODER_ERROR,
	// 控制器只读参数
	POS_CURRENT_SETPOINT_16HIGHER,
	POS_CURRENT_SETPOINT_16LOWER,
	VEL_CURRENT_SETPOINT_16HIGHER,
	VEL_CURRENT_SETPOINT_16LOWER,
	TORQUE_CURRENT_SETPOINT_16HIGHER,
	TORQUE_CURRENT_SETPOINT_16LOWER,
	CURRENT_LOOP_INTEGRATOR_16HIGHER,
	CURRENT_LOOP_INTEGRATOR_16LOWER,
	INPUT_FILTER_P_GAIN,
	INPUT_FILTER_I_GAIN,
	TRAJECTORY_DONE,
	ANTICOGGING_VALID,
	CONTROLLER_ERROR,
	// 电机只读参数
	A_PHASE_PWM_VALUE = 44,
	B_PHASE_PWM_VALUE,
	C_PHASE_PWM_VALUE,
	ARMED_STATE,
	IS_CALIBRATED,
	B_PHASE_CURRENT_MEASUREMENT,
	C_PHASE_CURRENT_MEASUREMENT,
	B_PHASE_CURRENT_CALIBRATION_VALUE,
	C_PHASE_CURRENT_CALIBRATION_VALUE,
	CURRENT_AMPLIFICATION,
	D_AXIS_CURRENT_INTEGRAL_TERM,
	Q_AXIS_CURRENT_INTEGRAL_TERM,
	IBUS,
	ALPHA_AXIS_VOLTAGE,
	BETA_AXIS_VOLTAGE,
	D_AXIS_CURRENT_TARGET_VALUE,
	Q_AXIS_CURRENT_TARGET_VALUE,
	D_AXIS_CURRENT_MEASUREMENT,
	Q_AXIS_CURRENT_MEASUREMENT,
	HARDWARE_MAX_ALLOWED_CURRENT,
	OVERCURRENT_TRIP_LEVEL,
	EFFECTIVE_CURRENT_LIM,
	DRV8301_ERROR,
	MOTOR_ERROR,
	// 热敏电阻只读参数
	INVERTER_CURRENT_TEMPERATURE = 69,
/************************************************************************RW************************************************************************/ 
	COM_DISCONNECT_PROTECTION_TIME = 200,//< 通信掉线保护时间 范围：0~3276MS
	INPUT_STATUS,                                //< BIT0、BIT1:IN1、IN2两路输入口状态
	OUTPUT_STATUS,                               //< BIT0、BIT1:OUT1、B-两路输出口状态
	FEEDBACK_POSITION_RESET,                      //< 反馈位置清零 范围: 0~3
	ABS_POSITION_RESET,                           //< 绝对位置模式当前位置清零
	LIMITED_PARKING_METHOD,                       //< 限位停车方式 
	MAX_MOTOR_SPEED,                          //< 电机最大转速
	ENCODER_COUNT,                						 //< 编码线数设置
	MOTOR_POLES,                         		//< 电机极对数
	CAN_ID,                   								//< CAN自定义驱动器节点号
	CAN_BAUD_RATE,                          //< CAN自定义波特率
	WHETHER_TO_STORE_PARA ,                //< 是否同步存储RW/S参数于EEPROM
	MOTOR_TEMPERATURE_PROTECTION_THRESHOLD,    //< 电值机温度保护阈值
	RATED_CURRENT,                               //< 额定电流
	CURRENTLOOP_P_GAIN,                  //电流环比例系数
	CURRENTLOOP_I_GAIN,
	VELOCITYLOOP_P_GAIN,                //速度环比例系数
	VELOCITYLOOP_I_GAIN,
	POSITIONLOOP_P_GAIN,              //位置环比例系数
	RS485_NODE_ID,                     
	RS485_NODE_BAUD_RATE,
	// 轴可读可写参数
	STARTUP_MOTOR_CALIBRATION = 222,
	STARTUP_ENCODER_INDEX_SEARCH,
	STARTUP_ENCODER_OFFSET_CALIBRATION,
	STARTUP_CLOSED_LOOP_CONTROL,
	ENABLE_WATCHDOG,
	WATCHDOG_TIMEOUT,
	CAN_HEARTBEAT_RATE_MS,
	CALIBRATION_LOCKIN_CURRENT,
	CALIBRATION_LOCKIN_RAMP_TIME,
	CALIBRATION_LOCKIN_RAMP_DISTANCE,
	CALIBRATION_LOCKIN_ACCEL,
	CALIBRATION_LOCKIN_VEL,
	CALIBRATION_LOCKIN_FINISH_DISTANCE,
	CALIBRATION_LOCKIN_FINISH_ON_VEL,
	CALIBRATION_LOCKIN_FINISH_ON_DISTANCE,
	CALIBRATION_LOCKIN_FINISH_ON_ENC_IDX,
	// 板子可读可写参数
	MAX_REGEN_CURRENT = 239,
	BRAKE_RESISTANCE,
	DC_BUS_UNDERVOLTAGE_TRIP_LEVEL,
	DC_BUS_OVERVOLTAGE_TRIP_LEVEL,
	ENABLE_DC_BUS_OVERVOLTAGE_RAMP,
	DC_BUS_OVERVOLTAGE_RAMP_START,
	DC_BUS_OVERVOLTAGE_RAMP_END,
	DC_MAX_POSITIVE_CURRENT,
	DC_MAX_NEGATIVE_CURRENT,
	// 编码器可读可写参数
	ENCODER_MODE = 249,
	USE_INDEX,
	ENCODER_PRE_CALIBRATED,
	ZERO_COUNT_ON_FIND_IDX,
	CPR,
	OFFSET,
	OFFSET_FLOAT,
	ENABLE_PHASE_INTERPOLATION,
	CALIB_RANGE,
	CALIB_SCAN_DISTANCE,
	ENCODER_BANDWIDTH,
	FIND_IDX_ON_LOCKIN_ONLY,
	IGNORE_ILLEGAL_HALL_STATE,
	// 控制器可读可写参数
		CONTROL_MODE = 263,
	//CONTROL_MODE,
	INPUT_MODE,
	VEL_RAMP_RATE,
	TORQUE_RAMP_RATE,
	INPUT_FILTER_BANDWIDTH,
	HOMING_SPEED,
	ENABLE_GAIN_SCHEDULING,
	GAIN_SCHEDULING_WIDTH,
	ENABLE_VEL_LIMIT,
	ENABLE_OVERSPEED_ERROR,
	VEL_LIMIT_TOLERANCE,
	ENABLE_CURRENT_MODE_VEL_LIMIT,
	// 电机可读可写参数
	MOTOR_PRE_CALIBRATED = 276,
	CALIBRATION_CURRENT,
	RESISTANCE_CALIB_MAX_VOLTAGE,
	PHASE_INDUCTANCE,
	PHASE_RESISTANCE,
	TORQUE_CONSTANT,
	MOTOR_DIRECTION,
	MOTOR_TYPE,
	CURRENT_LIM,
	CURRENT_LIM_MARGIN,
	TORQUE_LIM,
	REQUESTED_CURRENT_RANGE,
	CURRENT_CONTROL_BANDWIDTH,
	// 热敏电阻可读可写参数
	ENABLE_THERMISTOR_CURRENT_LIMIT = 290,
	INVERTER_TEMP_LIMIT_LOWER,
	INVERTER_TEMP_LIMIT_UPPER,
	// 梯形轨迹可读可写参数
	TRAPEZOIDAL_TRAJECTORY_VEL_LIMIT = 294,
	TRAPEZOIDAL_TRAJECTORY_ACCEL_LIMIT,
	TRAPEZOIDAL_TRAJECTORY_DECEL_LIMIT,
	// 命令参数
	TARGET_POSITION_16HIGHER = 298,
	TARGET_POSITION_16LOWER,
	POSITION_MODE_VEL_FF_16HIGHER,
	POSITION_MODE_VEL_FF_16LOWER,
	POSITION_MODE_TORQUE_FF_16HIGHER,
	POSITION_MODE_TORQUE_FF_16LOWER,
	TARGET_VEL_16HIGHER,
	TARGET_VEL_16LOWER,
	VEL_MODE_TORQUE_FF_16HIGHER,
	VEL_MODE_TORQUE_FF_16LOWER,
	TARGET_TORQUE_16HIGHER,
	TARGET_TORQUE_16LOWER,
	REQUESTED_STATE,
	CLEAR_ALL_ERRORS,
  INERTIA,
		
};





#endif

